### ISSUE TITLE
Create a second submit script for long nodes

### ISSUE THREAD

**Issue by CurtisColwell** [CurtisColwell/auto_slurm#3]
Currently when the script is submitted it defaults to a short node. A second script that submits jobs on a long node would be useful.

**Comment by icolwell** [comment]
What's the difference between the nodes? I think an argument to the script would make more sense.

**Comment by CurtisColwell** [comment]
One node just runs the job a lot longer than the other one. I think it would be better for the users if they just had two scripts, one for normal jobs and one for long nodes.

**Comment by icolwell** [comment]
Isn't the time a job takes defined by the complexity/processing requirements of the job itself? Or is the "long" node just underpowered compared to the "short" node? Or does the short node just cancel long jobs that are sent to it?

Anyway, my point is that you could just do something like:
`bash submit_gaussian.bash long` or `-l` or `-long` 
and
`bash submit_gaussian.bash short` or `-s` or `-short` 

then you wouldn't have duplicate code to maintain which is a pain.

**Comment by CurtisColwell** [comment]
Ok, I'll see if I can work this in. There are multiple possible nodes to submit to, but it will also have to default to short if nothing is there to grandfather in current users.

**Comment by CurtisColwell** [comment]
Ok, these changes have been implemented. Currently, if an invalid partition is inputted, the script errors out and does not submit jobs.
