### ISSUE TITLE
Double submitting

### ISSUE THREAD

**Issue by CurtisColwell** [CurtisColwell/auto_slurm#6]
So this is a bit of a weird one. When you submit a job, it checks for the same job in the queue, but when it reads the queue it only gets the first 8 characters of the job name. So if a job has a name that is longer than 8 characters it will submit a second job even if it is already running.

**Comment by CurtisColwell** [comment]
Made a new branch with a temporary solution

**Comment by CurtisColwell** [comment]
Merged temp fix

**Comment by CurtisColwell** [comment]
Pushed a fix that blocks submitting of jobs with the same first 8 characters as ones running in branch 6_double_submit

**Comment by icolwell** [comment]
Sounds like this was resolved in #23
